spring.application.name=spring-rest
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:student_directory}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Avocado*2002}



logging.level.root=warn

spring.main.banner-mode=off

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.jpa.hibernate.ddl-auto=update